#ifndef __ERROR_H__
#define __ERROR_H__

#define ERROR_CODE_NONE                 0
#define ERROR_CODE_UNKNOWN_COMMAND      -1
#define ERROR_CODE_INVALID_REQUEST      -2
#define ERROR_CODE_STORAGE_ENCRYPTED    -3
#define ERROR_CODE_SECRET_LOCKED        -4
#define ERROR_CODE_DRBG_EXHAUSTED       -5
#define ERROR_CODE_DRBG_NOT_INITIALIZED -6
#define ERROR_CODE_WRONG_KEY            -7
#define ERROR_CODE_KEY_SLOT_FULL        -8
#define	ERROR_CODE_KEY_NOT_FOUND		-9
#define ERROR_CODE_SECRET_SLOT_FULL     -10
#define ERROR_CODE_SECRET_NOT_FOUND     -11


#endif
